FROM freqtradeorg/freqtrade:stable

USER root

RUN apt-get update
RUN apt-get install -y python3-dev

USER ftuser

RUN pip3 install --user wheel freqtrade ta pandas-ta pytest pytest-mock pytest-subtests